import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppProviderWarappers from "./compnents/AppProviderWarappers";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "User Data Management Table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviderWarappers>
          {children}
        </AppProviderWarappers>
      </body>
    </html>
  );
}
